CREATE TABLE CLIENTE(
	COD_CLI SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(15) NOT NULL UNIQUE,
	CONTATO VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE FUNCIONARIO(
	COD_FUNCIONARIO SERIAL NOT NULL PRIMARY KEY,
	COD_CARGO INT NOT NULL REFERENCES CARGO(COD_CARGO) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	COD_LOJA INT NOT NULL REFERENCES LOJA(COD_LOJA) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(15) NOT NULL UNIQUE,
	CONTATO VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	--CONSTRAINT FK_CARGO FOREIGN KEY(COD_CARGO) REFERENCES CARGO(COD_CARGO) ON UPDATE CASCADE ON DELETE RESTRICT,
	--CONSTRAINT FK_LOJA FOREIGN KEY(COD_LOJA) REFERENCES LOJA(COD_LOJA) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CARGO(
	COD_CARGO SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SALARIO NUMERIC(8,2) NOT NULL
); 

CREATE TABLE PAGAMENTO(
	COD_PAGAMENTO SERIAL NOT NULL PRIMARY KEY,
	TIPO VARCHAR(50) NOT NULL
);

CREATE TABLE CATEGORIA(
	COD_CATEGORIA SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO TEXT NOT NULL
);

CREATE TABLE PRODUTO(
	COD_PRODUTO SERIAL NOT NULL PRIMARY KEY,
	COD_CATEGORIA INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	VALOR NUMERIC(8,2) NOT NULL,
	CONSTRAINT FK_CATEGORIA FOREIGN KEY(COD_CATEGORIA) REFERENCES CATEGORIA(COD_CATEGORIA) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE LOJA(
	COD_LOJA SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE ESTOQUE(
	COD_ESTOQUE SERIAL NOT NULL PRIMARY KEY, 
	COD_PRODUTO INT NOT NULL,
	COD_LOJA INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	CONSTRAINT FK_PRODUTO FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT FK_LOJA FOREIGN KEY(COD_LOJA) REFERENCES LOJA(COD_LOJA) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE PEDIDO(
	COD_PEDIDO SERIAL NOT NULL PRIMARY KEY,
	COD_CLIENTE INT NOT NULL,
	COD_FUNCIONARIO INT NOT NULL,
	COD_PAGAMENTO INT NOT NULL,
	VALOR_TOTAL NUMERIC(8,2) NOT NULL,
	DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PAGO BOOLEAN DEFAULT FALSE NOT NULL,
	CONSTRAINT FK_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT FK_FUNCIONARIO FOREIGN KEY(COD_FUNCIONARIO) REFERENCES FUNCIONARIO(COD_FUNCIONARIO) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT FK_PAGAMENTO FOREIGN KEY(COD_PAGAMENTO) REFERENCES PAGAMENTO(COD_PAGAMENTO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE ITEM_PEDIDO(
	COD_ITEM_PEDIDO SERIAL NOT NULL PRIMARY KEY,
	COD_PEDIDO INT NOT NULL,
	COD_ESTOQUE INT NOT NULL,
	QUANTIDADE INT NOT NULL,
	VALOR_TOTAL_ITEM NUMERIC(8,2) NOT NULL,
	CONSTRAINT FK_PEDIDO FOREIGN KEY(COD_PEDIDO) REFERENCES PEDIDO(COD_PEDIDO) ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT FK_ESTOQUE FOREIGN KEY(COD_ESTOQUE) REFERENCES ESTOQUE(COD_ESTOQUE) ON UPDATE CASCADE ON DELETE RESTRICT
);