----------------------------------------------------TRIGGERS-------------------------------------------------

CREATE OR REPLACE FUNCTION VERIFICAR_CLIENTE()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.NOME IS NOT NULL THEN
        IF EXISTS (SELECT * FROM CLIENTE WHERE NOME = NEW.NOME AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O NOME % JÁ ESTÁ EM USO POR OUTRO CLIENTE.', NEW.NOME;
        END IF;
    END IF;
	
    IF NEW.CPF IS NOT NULL THEN
        IF EXISTS (SELECT * FROM CLIENTE WHERE CPF = NEW.CPF AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O CPF % JÁ ESTÁ EM USO POR OUTRO CLIENTE.', NEW.CPF;
        END IF;
    END IF;

    IF NEW.EMAIL IS NOT NULL THEN
        IF EXISTS (SELECT * FROM CLIENTE WHERE EMAIL = NEW.EMAIL AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O EMAIL % JÁ ESTÁ EM USO POR OUTRO CLIENTE.', NEW.EMAIL;
        END IF;
    END IF;


    IF NEW.CONTATO IS NOT NULL THEN
        IF EXISTS (SELECT * FROM CLIENTE WHERE CONTATO = NEW.CONTATO AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O CONTATO % JÁ ESTÁ EM USO POR OUTRO CLIENTE.', NEW.CONTATO;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_VERIFICAR_CLIENTE
BEFORE INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
EXECUTE FUNCTION VERIFICAR_CLIENTE();

CREATE OR REPLACE FUNCTION VERIFICAR_CARGO()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.NOME IS NOT NULL THEN
        IF EXISTS (SELECT * FROM CARGO WHERE NOME = NEW.NOME AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O NOME DO CARGO % JÁ ESTÁ EM USO POR OUTRO CARGO.', NEW.NOME;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_VERIFICAR_CARGO
BEFORE INSERT OR UPDATE ON CARGO
FOR EACH ROW
EXECUTE FUNCTION VERIFICAR_CARGO();

CREATE OR REPLACE FUNCTION VERIFICAR_LOJA()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.NOME IS NOT NULL THEN
        IF EXISTS (SELECT * FROM LOJA WHERE NOME = NEW.NOME AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O NOME % JÁ ESTÁ EM USO POR OUTRO LOJA.', NEW.NOME;
        END IF;
    END IF;

    IF NEW.CNPJ IS NOT NULL THEN
        IF EXISTS (SELECT * FROM LOJA WHERE CNPJ = NEW.CNPJ AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O CNPJ % JÁ ESTÁ EM USO POR OUTRO LOJA.', NEW.CNPJ;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_VERIFICAR_LOJA
BEFORE INSERT OR UPDATE ON LOJA
FOR EACH ROW
EXECUTE FUNCTION VERIFICAR_LOJA();

CREATE OR REPLACE FUNCTION VERIFICAR_FUNCIONARIO()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.NOME IS NOT NULL THEN
        IF EXISTS (SELECT * FROM FUNCIONARIO WHERE NOME = NEW.NOME AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O NOME % JÁ ESTÁ EM USO POR OUTRO FUNCIONÁRIO.', NEW.NOME;
        END IF;
    END IF;

    IF NEW.CPF IS NOT NULL THEN
        IF EXISTS (SELECT * FROM FUNCIONARIO WHERE CPF = NEW.CPF AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O CPF % JÁ ESTÁ EM USO POR OUTRO FUNCIONÁRIO.', NEW.CPF;
        END IF;
    END IF;

    IF NEW.CONTATO IS NOT NULL THEN
        IF EXISTS (SELECT * FROM FUNCIONARIO WHERE CONTATO = NEW.CONTATO AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O CONTATO % JÁ ESTÁ EM USO POR OUTRO FUNCIONÁRIO.', NEW.CONTATO;
        END IF;
    END IF;
	
    IF NEW.EMAIL IS NOT NULL THEN
        IF EXISTS (SELECT * FROM FUNCIONARIO WHERE EMAIL = NEW.EMAIL AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O EMAIL % JÁ ESTÁ EM USO POR OUTRO FUNCIONÁRIO.', NEW.EMAIL;
        END IF;
    END IF;

    IF NEW.COD_CARGO IS NOT NULL THEN
        IF NOT EXISTS (SELECT * FROM CARGO WHERE COD = NEW.COD_CARGO) THEN
            RAISE EXCEPTION 'O CARGO NÃO EXISTE.';
        END IF;
    END IF;

    IF NEW.COD_LOJA IS NOT NULL THEN
        IF NOT EXISTS (SELECT * FROM LOJA WHERE COD = NEW.COD_LOJA) THEN
            RAISE EXCEPTION 'A LOJA NÃO EXISTE.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_VERIFICAR_FUNCIONARIO
BEFORE INSERT OR UPDATE ON FUNCIONARIO
FOR EACH ROW
EXECUTE FUNCTION VERIFICAR_FUNCIONARIO();

CREATE OR REPLACE FUNCTION VERIFICAR_PAGAMENTO()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.NOME IS NOT NULL THEN
        IF EXISTS (SELECT * FROM PAGAMENTO WHERE NOME = NEW.NOME AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O NOME DO PAGAMENTO % JÁ EXISTE.', NEW.NOME;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_VERIFICAR_PAGAMENTO
BEFORE INSERT OR UPDATE ON PAGAMENTO
FOR EACH ROW
EXECUTE FUNCTION VERIFICAR_PAGAMENTO();

CREATE OR REPLACE FUNCTION VERIFICAR_CATEGORIA()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.NOME IS NOT NULL THEN
        IF EXISTS (SELECT * FROM CATEGORIA WHERE NOME = NEW.NOME AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O NOME DA CATEGORIA % JÁ ESTÁ EM USO.', NEW.NOME;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_VERIFICAR_CATEGORIA
BEFORE INSERT OR UPDATE ON CATEGORIA
FOR EACH ROW
EXECUTE FUNCTION VERIFICAR_CATEGORIA();

CREATE OR REPLACE FUNCTION VERIFICAR_PRODUTO()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.NOME IS NOT NULL THEN
        IF EXISTS (SELECT * FROM PRODUTO WHERE NOME = NEW.NOME AND COD <> OLD.COD) THEN
            RAISE EXCEPTION 'O NOME DO PRODUTO % JÁ ESTÁ EM USO POR OUTRO PRODUTO.', NEW.NOME;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TG_VERFICAR_PRODUTO
BEFORE INSERT OR UPDATE ON PRODUTO
FOR EACH ROW
EXECUTE FUNCTION VERIFICAR_PRODUTO();

------------------------------------------------FUNCTIONS UPDATE-----------------------------------------------------

CREATE OR REPLACE FUNCTION UPDATE_CLIENTE(--DROP FUNCTION UPDATE_CLIENTE
	IDENTIFICADOR_C VARCHAR(100),
	NOME_C VARCHAR(100) DEFAULT NULL,
	CPF_C VARCHAR(15) DEFAULT NULL, 
	CONTATO_C VARCHAR(20) DEFAULT NULL, 
	EMAIL_C VARCHAR(50) DEFAULT NULL)
RETURNS TABLE(
	"id°" int,
	"Cliente" varchar,
	"Cpf" varchar,
	"Contato" varchar,
	"Email" varchar
) AS $$
BEGIN
	IF NOT EXISTS(SELECT * FROM CLIENTE WHERE CPF ILIKE IDENTIFICADOR_C OR NOME ILIKE IDENTIFICADOR_C ) THEN
		RAISE EXCEPTION 'O CLIENTE % NÃO EXISTE.', IDENTIFICADOR_C;
	ELSE
		UPDATE CLIENTE SET
			NOME = COALESCE(NOME_C, NOME),
			CPF = COALESCE(CPF_C, CPF),
			CONTATO = COALESCE(CONTATO_C, CONTATO),
			EMAIL = COALESCE(EMAIL_C, EMAIL)
		WHERE CPF ILIKE IDENTIFICADOR_C OR NOME ILIKE IDENTIFICADOR_C;

		IF NOT FOUND THEN
			RAISE EXCEPTION 'FALHA NA ATUALIZAÇÃO DO CLIENTE %.', IDENTIFICADOR_C;
		ELSE
			RAISE NOTICE 'CLIENTE ATUALIZADO COM SUCESSO.';
		END IF;
	END IF;
	
	RETURN QUERY
	SELECT cod, nome, cpf, contato, email FROM CLIENTE WHERE CPF ILIKE COALESCE(CPF_C, IDENTIFICADOR_C) OR NOME ILIKE COALESCE(NOME_C, IDENTIFICADOR_C);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION UPDATE_CARGO(--DROP FUNCTION UPDATE_CARGO
	IDENTIFICADOR_CAR VARCHAR(50),
	NOME_CAR VARCHAR(50) DEFAULT NULL, 
	SALARIO_CAR NUMERIC(8,2) DEFAULT NULL,
	COMISSAO_CAR NUMERIC(4,2) DEFAULT NULL)
RETURNS TABLE(
	"id°" int,
	"Cargo" varchar,
	"Salário" numeric,
	"Comissão" numeric
) AS $$
BEGIN 
	IF NOT EXISTS(SELECT * FROM CARGO WHERE NOME ILIKE IDENTIFICADOR_CAR) THEN 
		RAISE EXCEPTION 'O CARGO % NÃO EXISTE.', IDENTIFICADOR_CAR;
	ELSE 
		UPDATE CARGO SET 
			NOME = COALESCE(NOME_CAR, NOME),
			SALARIO = COALESCE(SALARIO_CAR, SALARIO),
			COMISSAO = COALESCE(COMISSAO_CAR, COMISSAO)
		WHERE NOME ILIKE IDENTIFICADOR_CAR;

		IF NOT FOUND THEN
			RAISE EXCEPTION 'FALHA NA ATUALIZAÇÃO DO CARGO %.', IDENTIFICADOR_CAR;
		ELSE
			RAISE NOTICE 'CARGO ATUALIZADO COM SUCESSO.';
		END IF;
	END IF;
	
	RETURN QUERY 
	SELECT cod, nome, salario, comissao FROM CARGO WHERE NOME ILIKE COALESCE(NOME_CAR, IDENTIFICADOR_CAR);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION UPDATE_LOJA(--DROP FUNCTION UPDATE_LOJA
	IDENTIFICADOR_L VARCHAR(50),
	NOME_L VARCHAR(20) DEFAULT NULL,
	CNPJ_L VARCHAR(18) DEFAULT NULL,
	ENDERECO_L TEXT DEFAULT NULL)
RETURNS TABLE(
	"id°" int,
	"Loja" varchar,
	"Cnpj" varchar,
	"Endereco" text
) AS $$
BEGIN 
	IF NOT EXISTS(SELECT * FROM LOJA WHERE NOME ILIKE IDENTIFICADOR_L) THEN
		RAISE EXCEPTION 'A % NÃO EXISTE.', IDENTIFICADOR_L;
	ELSE
		UPDATE LOJA SET 
			NOME = COALESCE(NOME_L,NOME),
			CNPJ = COALESCE(CNPJ_L, CNPJ),
			ENDERECO = COALESCE(ENDERECO_L, ENDERECO)
		WHERE NOME ILIKE IDENTIFICADOR_L;

		IF NOT FOUND THEN
			RAISE EXCEPTION 'FALHA NA ATUALIZAÇÃO DA %.', IDENTIFICADOR_NOME;
		ELSE
			RAISE NOTICE 'LOJA ATUALIZADA COM SUCESSO.';
		END IF;	
	END IF;
	
	RETURN QUERY 
		SELECT cod, nome, cnpj, endereco FROM LOJA WHERE NOME ILIKE COALESCE(NOME_L,IDENTIFICADOR_L);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION UPDATE_FUNCIONARIO( --DROP FUNCTION UPDATE_FUNCIONARIO
	IDENTIFICADOR_F VARCHAR(50),
	NOME_F VARCHAR(50) DEFAULT NULL,  
	CPF_F VARCHAR(50) DEFAULT NULL, 
	CONTATO_F VARCHAR(50) DEFAULT NULL, 
	EMAIL_F VARCHAR(50) DEFAULT NULL,
	NOME_CAR VARCHAR(50) DEFAULT NULL, 
	NOME_LOJ VARCHAR(20) DEFAULT NULL)
RETURNS TABLE(
	"id°" int,
	"Funcionario" varchar,
	"Cpf" varchar,
	"Contato" varchar,
	"Email" varchar,
	"Cargo" varchar,
	"Loja" varchar	
) AS $$
DECLARE
	COD_CAR INT; 
	COD_LOJ INT;
BEGIN	
	IF NOT EXISTS(SELECT * FROM FUNCIONARIO WHERE CPF ILIKE IDENTIFICADOR_F OR NOME ILIKE IDENTIFICADOR_F) THEN
		RAISE EXCEPTION 'O FUNCIONÁRIO % NÃO EXISTE.', IDENTIFICADOR_F;
	ELSE
	   	UPDATE FUNCIONARIO SET 
            NOME = COALESCE(NOME_F, NOME),
			CPF = COALESCE(CPF_F, CPF),
            CONTATO = COALESCE(CONTATO_F, CONTATO),
            EMAIL = COALESCE(EMAIL_F, EMAIL),
            COD_CARGO = COALESCE((SELECT COD FROM CARGO WHERE NOME ILIKE NOME_CAR), COD_CARGO),
            COD_LOJA = COALESCE((SELECT COD FROM LOJA WHERE NOME ILIKE NOME_LOJ), COD_LOJA)
        WHERE CPF ILIKE IDENTIFICADOR_F OR NOME ILIKE IDENTIFICADOR_F;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'FALHA NA ATUALIZAÇÃO DO FUNCIONÁRIO % ', IDENTIFICADOR_F;
        ELSE
            RAISE NOTICE 'FUNCIONÁRIO ATUALIZADO COM SUCESSO.';
        END IF;
	END IF;
	
	RETURN QUERY 
		SELECT f.cod, f.nome, cpf, contato, email, c.nome, l.nome FROM FUNCIONARIO F 
			JOIN CARGO C ON C.COD = F.COD_CARGO 
			JOIN LOJA L ON L.COD = F.COD_LOJA 
		WHERE CPF ILIKE COALESCE(CPF_F,IDENTIFICADOR_F) OR F.NOME ILIKE COALESCE(NOME_F,IDENTIFICADOR_F);	
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION UPDATE_PAGAMENTO(--DROP FUNCTION UPDATE_PAGAMENTO
	IDENTIFICADOR_PAG VARCHAR(50),
	NOME_PAG VARCHAR(50) DEFAULT NULL)
RETURNS TABLE(
	"id°" int,
	"Tipo Pagamento" varchar
) AS $$ 
BEGIN 
	IF NOT EXISTS(SELECT * FROM PAGAMENTO WHERE NOME = IDENTIFICADOR_PAG) THEN
		RAISE EXCEPTION 'O TIPO DE PAGAMENTO % NÃO EXISTE.', IDENTIFICADOR_PAG;
	ELSE 
		UPDATE PAGAMENTO SET NOME = NOME_PAG WHERE NOME ILIKE IDENTIFICADOR_PAG;
	
		IF NOT FOUND THEN
			RAISE EXCEPTION 'FALHA NA ATUALIZAÇÃO DO PAGAMENTO %', IDENTIFICADOR_PAG;
		END IF;
	
		RAISE NOTICE 'PAGAMENTO ATUALIZADO COM SUCESSO.';
	END IF;

	RETURN QUERY
		SELECT cod, nome FROM PAGAMENTO WHERE NOME ILIKE COALESCE(NOME_PAG,IDENTIFICADOR_PAG);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION UPDATE_CATEGORIA(--DROP FUNCTION UPDATE_CATEGORIA
	IDENTIFICADOR_C VARCHAR(50),
	NOME_C VARCHAR(50) DEFAULT NULL, 
	DESC_C TEXT DEFAULT NULL)
RETURNS TABLE(
	"id°" int,
	"Categoria" varchar,
	"Descrição" text
) AS $$ 
BEGIN 
	IF NOT EXISTS(SELECT * FROM CATEGORIA WHERE NOME ILIKE IDENTIFICADOR_C) THEN
		RAISE EXCEPTION 'A CATEGORIA % NÃO EXISTE.', IDENTIFICADOR_C;
	ELSE
		UPDATE CATEGORIA SET 
			NOME = COALESCE(NOME_C, NOME),
			DESCRICAO = COALESCE(DESC_C, DESCRICAO)
		WHERE NOME ILIKE IDENTIFICADOR_C;
	
		IF NOT FOUND THEN
			RAISE EXCEPTION 'FALHA NA ATUALIZAÇÃO DA CATEGORIA %', IDENTIFICADOR_C;
		END IF;
	
		RAISE NOTICE 'CATEGORIA ATUALIZADA COM SUCESSO.';
	END IF;
	
	RETURN QUERY
		SELECT cod, nome, descricao FROM CATEGORIA WHERE NOME ILIKE COALESCE(NOME_C,IDENTIFICADOR_C);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION UPDATE_PRODUTO( --DROP FUNCTION UPDATE_PRODUTO
	IDENTIFICADOR_P VARCHAR(100),
	NOME_P VARCHAR(50) DEFAULT NULL, 
	NOME_CAT VARCHAR(50) DEFAULT NULL,
	VALOR_P NUMERIC(8,2) DEFAULT NULL)
RETURNS TABLE(
	"id°" int,
	"Produto" varchar,
	"Categoria" varchar,
	"Valor Unitário" numeric
) AS $$
BEGIN 
	IF NOT EXISTS(SELECT * FROM PRODUTO WHERE NOME ILIKE IDENTIFICADOR_P) THEN
		RAISE EXCEPTION 'O PRODUTO % NÃO EXISTE.', IDENTIFICADOR_P;	
	ELSE 
		UPDATE PRODUTO SET 
			NOME = COALESCE(NOME_P,NOME),
			VALOR_UNITARIO = COALESCE(VALOR_P, VALOR_UNITARIO),
			COD_CATEGORIA = COALESCE((SELECT COD FROM CATEGORIA WHERE NOME ILIKE NOME_CAT), COD_CATEGORIA)
		WHERE NOME ILIKE IDENTIFICADOR_P;
	
		IF NOT FOUND THEN
			RAISE EXCEPTION 'FALHA NA ATUALIZAÇÃO DO PRODUTO % ', IDENTIFICADOR_P;
		ELSE
			RAISE NOTICE 'PRODUTO ATUALIZADO COM SUCESSO.';
		END IF;
	END IF;

	RETURN QUERY 
		SELECT p.cod, p.nome, c.nome, valor_unitario FROM PRODUTO P
			JOIN CATEGORIA C ON C.COD = P.COD_CATEGORIA
		WHERE P.NOME ILIKE COALESCE(NOME_P,IDENTIFICADOR_P);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION UPDATE_ESTOQUE( --DROP FUNCTION UPDATE_ESTOQUE
	IDENTIFICADOR_E VARCHAR(100),
	NOME_P VARCHAR(50) DEFAULT NULL, 
	NOME_L VARCHAR(20) DEFAULT NULL,
	QUANT INT DEFAULT NULL)
RETURNS TABLE(
	"id°" int,
	"Produto" varchar,
	"Loja" varchar,
	"Quantidade" int
) AS $$
DECLARE
	COD_PROD INT;
	COD_LOJ INT;
	NOME_PROD VARCHAR;
	NOME_LOJ VARCHAR;
	COD_E INT;
BEGIN
	SELECT COD, NOME INTO COD_PROD, NOME_PROD FROM PRODUTO WHERE NOME ILIKE SPLIT_PART(IDENTIFICADOR_E,'-',1);
	SELECT COD, NOME INTO COD_LOJ, NOME_LOJ FROM LOJA WHERE NOME ILIKE SPLIT_PART(IDENTIFICADOR_E,'-',2);

	SELECT COD INTO COD_E FROM ESTOQUE WHERE COD_PRODUTO = COD_PROD AND COD_LOJA = COD_LOJ;
	
	IF NOT EXISTS(SELECT * FROM ESTOQUE WHERE COD = COD_E) THEN  
		RAISE EXCEPTION 'O ESTOQUE DO PRODUTO E LOJA INFORMADO NÃO EXISTE.';
	ELSE
		UPDATE ESTOQUE SET 
			COD_PRODUTO = COALESCE((SELECT COD FROM PRODUTO WHERE NOME ILIKE NOME_P), COD_PRODUTO),
			COD_LOJA = COALESCE((SELECT COD FROM LOJA WHERE NOME ILIKE NOME_L), COD_LOJA),
			QUANTIDADE = COALESCE(QUANT, QUANTIDADE)
		WHERE COD = COD_E;

		IF NOT FOUND THEN
			RAISE EXCEPTION 'FALHA NA ATUALIZAÇÃO DO PRODUTO % e %', NOME_PROD, NOME_LOJ;
		ELSE
			RAISE NOTICE 'ESTOQUE ATUALIZADO COM SUCESSO.';
		END IF;
	END IF;
	
	RETURN QUERY 
		SELECT e.cod, p.nome, l.nome, quantidade FROM ESTOQUE E 
			JOIN PRODUTO P ON P.COD = E.COD_PRODUTO
			JOIN LOJA L ON L.COD = E.COD_LOJA
		WHERE E.COD = COD_E;
END;
$$ LANGUAGE PLPGSQL;

---------------------------------------------FUNCÃO ALTERAR----------------------------------------------------------

CREATE OR REPLACE FUNCTION ALTERAR(--CARGO DROP FUNCTION ALTERAR(char_cargo,VARCHAR,VARCHAR,NUMERIC,NUMERIC)
	TABELA VARCHAR(50),
	IDENTIFICADOR VARCHAR(50),
	CARGO VARCHAR(50) DEFAULT NULL, 
	SALARIO NUMERIC(8,2) DEFAULT NULL, 
	COMISSAO NUMERIC(4,2) DEFAULT NULL)
RETURNS TABLE(
	"id°" int,
	"Cargo" varchar,
	"Salário" numeric,
	"Comissão" numeric	
) AS $$
BEGIN 
	IF TABELA ILIKE 'CARGO' THEN
		IF IDENTIFICADOR IS NOT NULL THEN
			RETURN QUERY
			SELECT * FROM UPDATE_CARGO(IDENTIFICADOR, CARGO, SALARIO, COMISSAO);
		ELSE
			RAISE EXCEPTION 'PARÂMETRO IDENTIFICADOR VÁZIO. POR FAVOR, TENTE NOVAMENTE.';
		END IF;
		RETURN;
	ELSIF TABELA ILIKE 'CLIENTE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CLIENTE.';
	ELSIF TABELA ILIKE 'LOJA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA LOJA.';
	ELSIF TABELA ILIKE 'FUNCIONARIO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA FUNCIONÁRIO.';
	ELSIF TABELA ILIKE 'PAGAMENTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PAGAMENTO.';
	ELSIF TABELA ILIKE 'CATEGORIA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CATEGORIA.';
	ELSIF TABELA ILIKE 'PRODUTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PRODUTO.';
	ELSIF TABELA ILIKE 'ESTOQUE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA ESTOQUE.';
	ELSE
		RAISE EXCEPTION 'TABELA NÃO ENCONTRADA. POR FAVOR, VERIFIQUE O NOME E TENTE NOVAMENTE';
	END IF;
END;
$$ LANGUAGE PLPGSQL;--a partir do 4° atributo, se passar nulo, especificar o tipo numeric (null::numeric)
--select * from alterar('cargo', 'Gerente', 'Vendedor', null,null::numeric)
CREATE OR REPLACE FUNCTION ALTERAR(--LOJA DROP FUNCTION ALTERAR(VARCHAR,VARCHAR,VARCHAR,NUMERIC,NUMERIC)
	TABELA VARCHAR(50),
	IDENTIFICADOR VARCHAR(50),
	LOJA VARCHAR(50),
	CNPJ VARCHAR(18),
	ENDERECO TEXT)
RETURNS TABLE(
	"id°" int,
	"Loja" varchar,
	"Cnpj" varchar,
	"Endereco" text	
) AS $$
BEGIN
	IF TABELA ILIKE 'LOJA' THEN
		IF IDENTIFICADOR IS NOT NULL THEN
			RETURN QUERY 
			SELECT * FROM UPDATE_LOJA(IDENTIFICADOR, LOJA, CNPJ, ENDERECO);
		ELSE 
			RAISE EXCEPTION 'PARÂMETRO IDENTIFICADOR VÁZIO. POR FAVOR, TENTE NOVAMENTE .';
		END IF;
		RETURN;
	ELSIF TABELA ILIKE 'CARGO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CARGO.';
	ELSIF TABELA ILIKE 'PAGAMENTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PAGAMENTO.';
	ELSIF TABELA ILIKE 'FUNCIONARIO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA FUNCIONÁRIO.';
	ELSIF TABELA ILIKE 'CLIENTE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CLIENTE.';
	ELSIF TABELA ILIKE 'CATEGORIA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CATEGORIA.';
	ELSIF TABELA ILIKE 'PRODUTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PRODUTO.';
	ELSIF TABELA ILIKE 'ESTOQUE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA ESTOQUE.';
	ELSE
		RAISE EXCEPTION 'TABELA NÃO ENCONTRADA. POR FAVOR, VERIFIQUE O NOME E TENTE NOVAMENTE';
	END IF;	
END;
$$ LANGUAGE PLPGSQL;
--select * from alterar('loja', 'Loja 1', 'Loja 2',null,null);
CREATE OR REPLACE FUNCTION ALTERAR(--PAGAMENTO DROP FUNCTION ALTERAR(varchar,VARCHAR,VARCHAR)
	TABELA VARCHAR(9),
	IDENTIFICADOR VARCHAR(50),
	PAGAMENTO VARCHAR(50),
	ATRIB_EXTRA INT)
RETURNS TABLE(
	"id°" int,
	"Tipo Pagamento" varchar	
) AS $$
BEGIN
	IF TABELA ILIKE 'PAGAMENTO' THEN
		IF IDENTIFICADOR IS NOT NULL THEN
			RETURN QUERY
			SELECT * FROM UPDATE_PAGAMENTO(IDENTIFICADOR, PAGAMENTO);
		ELSE
			RAISE EXCEPTION 'PARÂMETRO IDENTIFICADOR VÁZIO. POR FAVOR, TENTE NOVAMENTE.';
		END IF;
		RETURN;
	ELSIF TABELA ILIKE 'CARGO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CARGO.';
	ELSIF TABELA ILIKE 'LOJA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA LOJA.';
	ELSIF TABELA ILIKE 'FUNCIONARIO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS FUNCIONÁRIO.';
	ELSIF TABELA ILIKE 'CLIENTE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CLIENTE.';
	ELSIF TABELA ILIKE 'CATEGORIA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CATEGORIA.';
	ELSIF TABELA ILIKE 'PRODUTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PRODUTO.';
	ELSIF TABELA ILIKE 'ESTOQUE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA ESTOQUE.';
	ELSE
		RAISE EXCEPTION 'TABELA NÃO ENCONTRADA. POR FAVOR, VERIFIQUE O NOME E TENTE NOVAMENTE';
	END IF;	
END;
$$ LANGUAGE PLPGSQL;--no ultimo atributo, obrigatorio passar nulo e especificar o tipo int (null::int)
--select * from alterar('pagamento', 'Pix', 'Dinheiro', null::int)
CREATE OR REPLACE FUNCTION ALTERAR(--CATEGORIA DROP FUNCTION ALTERAR(VARCHAR,VARCHAR,VARCHAR,TEXT)
	TABELA VARCHAR(50),
	IDENTIFICADOR VARCHAR(50),
	CATEGORIA VARCHAR(50), 
	DESCRICAO TEXT)
RETURNS TABLE(
	"id°" int,
	"Categoria" varchar,
	"Descrição" text	
) AS $$
BEGIN 
	IF TABELA ILIKE 'CATEGORIA' THEN
		IF IDENTIFICADOR IS NOT NULL THEN
			RETURN QUERY
			SELECT * FROM UPDATE_CATEGORIA(IDENTIFICADOR, CATEGORIA, DESCRICAO);
		ELSE
			RAISE EXCEPTION 'PARÂMETRO IDENTIFICADOR VÁZIO. POR FAVOR, TENTE NOVAMENTE.';
		END IF;
		RETURN;
	ELSIF TABELA ILIKE 'CARGO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CARGO.';
	ELSIF TABELA ILIKE 'LOJA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA LOJA.';
	ELSIF TABELA ILIKE 'FUNCIONARIO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA FUNCIONÁRIO.';
	ELSIF TABELA ILIKE 'PAGAMENTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PAGAMENTO.';
	ELSIF TABELA ILIKE 'CLIENTE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CLIENTE.';
	ELSIF TABELA ILIKE 'PRODUTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PRODUTO.';
	ELSIF TABELA ILIKE 'ESTOQUE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA ESTOQUE.';
	ELSE
		RAISE EXCEPTION 'TABELA NÃO ENCONTRADA. POR FAVOR, VERIFIQUE O NOME E TENTE NOVAMENTE';
	END IF;
END;
$$ LANGUAGE PLPGSQL;
--select * from alterar('categoria', 'Camisetas', 'Calças Jeans', null);
CREATE OR REPLACE FUNCTION ALTERAR(--CLIENTE DROP FUNCTION ALTERAR(VARCHAR,VARCHAR,VARCHAR,VARCHAR,VARCHAR,VARCHAR,extra)
	TABELA VARCHAR(7),
	IDENTIFICADOR VARCHAR(100), 
	CLIENTE VARCHAR(100), 
	CPF VARCHAR(15),
	CONTATO VARCHAR(20), 
	EMAIL VARCHAR(50))
RETURNS TABLE(
	"id°" int,
	"Cliente" varchar,
	"Cpf" varchar,
	"Contato" varchar,
	"Email" varchar	
) AS $$
DECLARE
BEGIN 
	IF TABELA ILIKE 'CLIENTE' THEN
		IF IDENTIFICADOR IS NOT NULL THEN
			RETURN QUERY
			SELECT * FROM UPDATE_CLIENTE(IDENTIFICADOR,CLIENTE,CPF,CONTATO,EMAIL);
		ELSE
			RAISE EXCEPTION 'PARÂMETRO IDENTIFICADOR VÁZIO. POR FAVOR, TENTE NOVAMENTE.';
		END IF;
		RETURN;
	ELSIF TABELA ILIKE 'CARGO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CARGO.';
	ELSIF TABELA ILIKE 'LOJA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA LOJA.';
	ELSIF TABELA ILIKE 'FUNCIONARIO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA FUNCIONÁRIO.';
	ELSIF TABELA ILIKE 'PAGAMENTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PAGAMENTO.';
	ELSIF TABELA ILIKE 'CATEGORIA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CATEGORIA.';
	ELSIF TABELA ILIKE 'PRODUTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PRODUTO.';
	ELSIF TABELA ILIKE 'ESTOQUE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA ESTOQUE.';
	ELSE
		RAISE EXCEPTION 'TABELA NÃO ENCONTRADA. POR FAVOR, VERIFIQUE O NOME E TENTE NOVAMENTE';
	END IF;
END;
$$ LANGUAGE PLPGSQL;
--select * from alterar('cliente', '987.654.321-00', 'João Oliveira de Menezes',null,null,null)
CREATE OR REPLACE FUNCTION ALTERAR(--FUNCIONARIO DROP FUNCTION ALTERAR(VARCHAR,VARCHAR,VARCHAR,VARCHAR,VARCHAR,VARCHAR,VARCHAR,VARCHAR,extra)
	TABELA VARCHAR(50), 
	IDENTIFICADOR VARCHAR(100), 
	FUNCIONARIO VARCHAR(100),
	CPF VARCHAR(15),
	CONTATO VARCHAR(20), 
	EMAIL VARCHAR(50),
	NOME_CAR VARCHAR(50), 
	NOME_LOJ VARCHAR(20))
RETURNS TABLE(
	"id°" int,
	"Funcionario" varchar,
	"Cpf" varchar,
	"Contato" varchar,
	"Email" varchar,
	"Cargo" varchar,
	"Loja" varchar	
) AS $$
DECLARE
BEGIN 
	IF TABELA ILIKE 'FUNCIONARIO' THEN
		IF IDENTIFICADOR IS NOT NULL THEN
			RETURN QUERY
			SELECT * FROM UPDATE_FUNCIONARIO(IDENTIFICADOR,FUNCIONARIO,CPF,CONTATO,EMAIL,NOME_CAR,NOME_LOJ);
		ELSE 
			RAISE EXCEPTION 'PARÂMETRO IDENTIFICADOR VÁZIO. POR FAVOR, TENTE NOVAMENTE.';
		END IF;
		RETURN;
	ELSIF TABELA ILIKE 'CARGO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CARGO.';
	ELSIF TABELA ILIKE 'LOJA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA LOJA.';
	ELSIF TABELA ILIKE 'CLIENTE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CLIENTE.';
	ELSIF TABELA ILIKE 'PAGAMENTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PAGAMENTO.';
	ELSIF TABELA ILIKE 'CATEGORIA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CATEGORIA.';
	ELSIF TABELA ILIKE 'PRODUTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PRODUTO.';
	ELSIF TABELA ILIKE 'ESTOQUE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA ESTOQUE.';
	ELSE
		RAISE EXCEPTION 'TABELA NÃO ENCONTRADA. POR FAVOR, VERIFIQUE O NOME E TENTE NOVAMENTE';
	END IF;
END;
$$ LANGUAGE PLPGSQL;
--select * from alterar('funcionario', 'Ana Costa','Ana da Costa Silveira',null,null,'anacsilveira@email.com',null,null)
CREATE OR REPLACE FUNCTION ALTERAR(--PRODUTO DROP FUNCTION ALTERAR(varchar,VARCHAR,VARCHAR,VARCHAR,NUMERIC, FLOAT)
	TABELA VARCHAR(7),
	IDENTIFICADOR VARCHAR(100),
	PRODUTO VARCHAR(50) DEFAULT NULL,
	CATEGORIA VARCHAR(50) DEFAULT NULL,
	VALOR NUMERIC(8,2) DEFAULT NULL)
RETURNS TABLE(
	"id°" int,
	"Produto" varchar,
	"Categoria" varchar,
	"Valor Unitário" numeric
) AS $$
DECLARE
BEGIN 
	IF TABELA ILIKE 'PRODUTO' THEN
		IF IDENTIFICADOR IS NOT NULL THEN
			RETURN QUERY
			SELECT * FROM UPDATE_PRODUTO(IDENTIFICADOR, PRODUTO, CATEGORIA, VALOR);
		ELSE
			RAISE EXCEPTION 'PARÂMETRO IDENTIFICADOR VÁZIO. POR FAVOR, TENTE NOVAMENTE.';
		END IF;
		RETURN;
	ELSIF TABELA ILIKE 'CARGO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CARGO.';
	ELSIF TABELA ILIKE 'LOJA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA LOJA.';
	ELSIF TABELA ILIKE 'FUNCIONARIO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA FUNCIONÁRIO.';
	ELSIF TABELA ILIKE 'PAGAMENTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PAGAMENTO.';
	ELSIF TABELA ILIKE 'CATEGORIA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CATEGORIA.';
	ELSIF TABELA ILIKE 'CLIENTE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CLIENTE.';
	ELSIF TABELA ILIKE 'ESTOQUE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA ESTOQUE.';
	ELSE
		RAISE EXCEPTION 'TABELA NÃO ENCONTRADA. POR FAVOR, VERIFIQUE O NOME E TENTE NOVAMENTE';
	END IF;
END;
$$ LANGUAGE PLPGSQL;--no ultimo atributo, se passar nulo, especificar o tipo int (null::numeric)
--select * from alterar('produto', 'Camiseta Básica',null,'Loja 1',null::numeric)
CREATE OR REPLACE FUNCTION ALTERAR(--ESTOQUE DROP FUNCTION ALTERAR(VARCHAR,varchar,VARCHAR,VARCHAR,INT,INT)
	TABELA VARCHAR(50), 
	IDENTIFICADOR VARCHAR(100),
	PRODUTO VARCHAR(50) DEFAULT NULL, 
	LOJA VARCHAR(50) DEFAULT NULL,
	QUANTIDADE INT DEFAULT NULL)
RETURNS TABLE(
	"id°" int,
	"Produto" varchar,
	"Loja" varchar,
	"Quantidade" int	
) AS $$
DECLARE
BEGIN 
	IF TABELA ILIKE 'ESTOQUE' THEN
		IF IDENTIFICADOR IS NOT NULL THEN
			RETURN QUERY
			SELECT * FROM UPDATE_ESTOQUE(IDENTIFICADOR,PRODUTO,LOJA,QUANTIDADE);
		ELSE 
			RAISE EXCEPTION 'PARÂMETRO IDENTIFICADOR VÁZIO. POR FAVOR, TENTE NOVAMENTE.';
		END IF;
		RETURN;
	ELSIF TABELA ILIKE 'CARGO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CARGO.';
	ELSIF TABELA ILIKE 'LOJA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA LOJA.';
	ELSIF TABELA ILIKE 'FUNCIONARIO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA FUNCIONÁRIO.';
	ELSIF TABELA ILIKE 'PAGAMENTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PAGAMENTO.';
	ELSIF TABELA ILIKE 'CATEGORIA' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CATEGORIA.';
	ELSIF TABELA ILIKE 'PRODUTO' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA PRODUTO.';
	ELSIF TABELA ILIKE 'CLIENTE' THEN
		RAISE EXCEPTION 'PARÂMETROS INCORRETOS PARA A TABELA CLIENTE.';
	ELSE
		RAISE EXCEPTION 'TABELA NÃO ENCONTRADA. POR FAVOR, VERIFIQUE O NOME E TENTE NOVAMENTE';
	END IF;
END;
$$ LANGUAGE PLPGSQL;--no ultimo atributo, se passar nulo, especificar o tipo int (null::int)
--select * from alterar('estoque', 'Camiseta Básica-Loja 2',null,'Loja 1',null::int)