-----------------------GERENCIAMENTO DE USUÁRIOS E PERMISSÕES DE ACESSO----------------------------------------------------
--USUARIOS
	--loja 1
CREATE USER "JOÃO SILVA";
CREATE USER "CARLOS SANTOS";
CREATE USER "ANA COSTA";
	--loja 2
CREATE USER "LUCAS ALMEIDA";
CREATE USER "ROBERTO PEREIRA";
CREATE USER "JULIANA MARTINS";

--GERENTE
CREATE ROLE GERENTE;
ALTER USER GERENTE SUPERUSER;

GRANT GERENTE TO "JOÃO SILVA";
GRANT GERENTE TO "LUCAS ALMEIDA";

--VENDEDOR
CREATE ROLE VENDEDOR;
GRANT VENDEDOR TO "ANA COSTA";
GRANT VENDEDOR TO "JULIANA MARTINS";

--OPERADOR DE CAIXA
CREATE ROLE OPERADOR_DE_CAIXA;
GRANT OPERADOR_DE_CAIXA TO "CARLOS SANTOS";
GRANT OPERADOR_DE_CAIXA TO "ROBERTO PEREIRA";

	--TABELAS
	GRANT SELECT,INSERT,UPDATE ON PEDIDO,ITEM_PEDIDO,CREDIARIO TO OPERADOR_DE_CAIXA;
	GRANT SELECT ON CLIENTE,PAGAMENTO TO OPERADOR_DE_CAIXA;

	GRANT SELECT ON VER_CLIENTE, VER_PRODUTO TO OPERADOR_DE_CAIXA;

	GRANT EXECUTE ON FUNCTION CONTROLE_ESTOQUE() TO OPERADOR_DE_CAIXA;
	GRANT EXECUTE ON FUNCTION NOTA_FISCAL(COD_P INT) TO OPERADOR_DE_CAIXA;
	GRANT EXECUTE ON FUNCTION ADD_PEDIDO(IDENTIFICADOR_C VARCHAR(100),NOME_P VARCHAR(50),QUANT_V INT,NOME_PAG VARCHAR(50),IDENTIFICADOR_F VARCHAR(100),QUANT_PARCELA INT) TO OPERADOR_DE_CAIXA;
	GRANT EXECUTE ON FUNCTION PAGAR_PEDIDO(IDENTIFICADOR_C VARCHAR(100)) TO OPERADOR_DE_CAIXA;
	GRANT EXECUTE ON FUNCTION RELATORIO_PEDIDO(DT_I DATE, DT_F DATE) TO OPERADOR_DE_CAIXA;

	GRANT EXECUTE ON FUNCTION CARNE_CREDIARIO(COD_P INT) TO OPERADOR_DE_CAIXA;
	GRANT EXECUTE ON FUNCTION CREDIARIO(COD_P INT, QUANT_P INT) TO OPERADOR_DE_CAIXA;
	GRANT EXECUTE ON FUNCTION PAGAR_CREDIARIO(IDENTIFICADOR_C VARCHAR(100), DATA_PAG TIMESTAMP) TO OPERADOR_DE_CAIXA;

--GERENTE
SET ROLE "JOÃO SILVA";
SET ROLE GERENTE;

RESET ROLE;

--VENDEDOR
SET ROLE "ANA COSTA";
SET ROLE VENDEDOR;

RESET ROLE;

--OPERADOR DE CAIXA
SET ROLE "CARLOS SANTOS";
SET ROLE OPERADOR_DE_CAIXA;

RESET ROLE;

/*

--RENOMEAR UM USUÁRIO
ALTER USER NOME RENAME TO NEWNOME;

--ADICIONAR UM USÁRIO A UM GRUPO
ALTER GROUP NOMEGRUPO ADD USER NOMEUSUARIO;

--REMOVER UM USUÁRIO
ALTER GROUP NOMEGRUPO DROP USER NOMEUSUARIO;

--REMOVER UM GRUPO
DROP GROUP NOMEGRUPO

--RENOMEAR UM GRUPO
ALTER GROUP NOMEGRUPO RENAME TO NEWNOMEGRUPO;

--para saber qual usuário esta conectado atualmente
SELECT current_user;
*/