-----------------------GERENCIAMENTO DE USUÁRIOS E PERMISSÕES DE ACESSO----------------------------------------------------
--USUARIOS
	--loja 1
CREATE USER "JOÃO SILVA";
CREATE USER "CARLOS SANTOS";
CREATE USER "ANA COSTA";
	--loja 2
CREATE USER "LUCAS ALMEIDA";
CREATE USER "ROBERTO PEREIRA";
CREATE USER "JULIANA MARTINS";

--GERENTE
CREATE ROLE GERENTE;
ALTER USER GERENTE SUPERUSER;
GRANT GERENTE TO "JOÃO SILVA";
GRANT GERENTE TO "LUCAS ALMEIDA";
	
--VENDEDOR
CREATE ROLE VENDEDOR;
GRANT VENDEDOR TO "ANA COSTA";
GRANT VENDEDOR TO "JULIANA MARTINS";

--OPERADOR DE CAIXA
CREATE ROLE OPERADOR_DE_CAIXA;
GRANT OPERADOR_DE_CAIXA TO "Carlos Santos";
GRANT OPERADOR_DE_CAIXA TO "Roberto Pereira";

	--TABELAS
	GRANT SELECT,INSERT,UPDATE ON PEDIDO,ITEM_PEDIDO,CREDIARIO TO OPERADOR_DE_CAIXA;
	GRANT SELECT ON CLIENTE,PAGAMENTO TO OPERADOR_DE_CAIXA;

	GRANT SELECT ON VER_CLIENTE, PEDIDOS, CARNE_CREDIARIO TO OPERADOR_DE_CAIXA;

	GRANT EXECUTE ON FUNCTION CONTROLE_ESTOQUE() TO OPERADOR_DE_CAIXA;
	GRANT EXECUTE ON FUNCTION NOTA_FISCAL(COD_P INT) TO OPERADOR_DE_CAIXA;
	GRANT EXECUTE ON FUNCTION ADD_PEDIDO(IDENTIFICADOR_C VARCHAR(100),NOME_P VARCHAR(50),QUANT_V INT,NOME_PAG VARCHAR(50),IDENTIFICADOR_F VARCHAR(100),QUANT_PARCELA INT DEFAULT 0) TO OPERADOR_DE_CAIXA;
	GRANT EXECUTE ON FUNCTION PAGAR_PEDIDO(IDENTIFICADOR_C VARCHAR(100)) TO OPERADOR_DE_CAIXA;

	GRANT EXECUTE ON FUNCTION CARNE_CREDIARIO(COD_P INT) TO OPERADOR_DE_CAIXA;
	GRANT EXECUTE ON FUNCTION CREDIARIO(COD_P INT, QUANT_P INT) TO OPERADOR_DE_CAIXA;
	GRANT EXECUTE ON FUNCTION PAGAR_CREDIARIO(IDENTIFICADOR_C VARCHAR(100), DATA_PAG TIMESTAMP DEFAULT CURRENT_TIMESTAMP) TO OPERADOR_DE_CAIXA;
	
	--FUNCOES


--ENTRAR E SAIR DE UM USUARIO/ROLE
--RENOMEAR UM USUÁRIO
ALTER USER NOME RENAME TO NEWNOME

--ADICIONAR UM USÁRIO A UM GRUPO
ALTER GROUP NOMEGRUPO ADD USER NOMEUSUARIO;

--REMOVER UM USUÁRIO
ALTER GROUP NOMEGRUPO DROP USER NOMEUSUARIO;

--REMOVER UM GRUPO
DROP GROUP NOMEGRUPO

--RENOMEAR UM GRUPO
ALTER GROUP NOMEGRUPO RENAME TO NEWNOMEGRUPO;

--PARA ENTRAR EM UM USUÁRIO
SET ROLE 'NOMEDOUSUÁRIO';
SET ROLE GROOMER;

--SAIR DO USUÁRIO
