-----------------------GERENCIAMENTO DE USUÁRIOS E PERMISSÕES DE ACESSO----------------------------------------------------
--USUARIOS
	--loja 1
CREATE USER "João Silva" WITH SENHA;
CREATE USER "Carlos Santos" WITH SENHA;
CREATE USER "Ana Costa" WITH SENHA;
	--loja 2
CREATE USER "Lucas Almeida" WITH SENHA;
CREATE USER "Roberto Pereira" WITH SENHA;
CREATE USER "Juliana Martins" WITH SENHA;

--USUARIO->ROLES
GRANT GERENTE TO "João Silva"
GRANT OPERADOR_DE_CAIXA TO "Carlos Santos"
GRANT VENDEDOR TO "Ana Costa"

GRANT GERENTE TO "Lucas Almeida"
GRANT OPERADOR_DE_CAIXA TO "Roberto Pereira"
GRANT VENDEDOR TO "Juliana Martins"

--GERENTE
CREATE ROLE GERENTE;
ALTER USER GERENTE SUPERUSER;
	
--VENDEDOR
CREATE ROLE VENDEDOR
	--TABELAS
	GRANT SELECT ON NOME_TABELA TO VENDEDOR
	--FUNCOES
	
--OPERADOR DE CAIXA
CREATE ROLE OPERADOR_DE_CAIXA
	--TABELAS
	GRANT SELECT ON NOME_TABELA TO OPERADOR_DE_CAIXA
	--FUNCOES


--ENTRAR E SAIR DE UM USUARIO/ROLE
