@startuml Diagrama de Classe - Biblioteca
' Classe Livro
class Livro {
    + String titulo
    + String autor
    + String isbn
    + Boolean disponivel
    + void emprestar()
    + void devolver()
}

' Classe Cliente
class Cliente {
    + String nome
    + Integer id
    + String telefone
    + String endereco
    + void realizarEmprestimo()
    + void devolverLivro()
}

' Classe Empréstimo
class Emprestimo {
    + Date dataEmprestimo
    + Date dataDevolucao
    + Livro livro
    + Cliente cliente
    + void calcularMulta()
    + void finalizarEmprestimo()
}

' Classe Funcionário
class Funcionario {
    + String nome
    + Integer matricula
    + String cargo
    + void registrarEmprestimo()
    + void registrarDevolucao()
}

' Relacionamentos
Cliente "1" -- "0..*" Emprestimo : realiza
Livro "1" --> "0..*" Emprestimo : está associado
Funcionario "1" --> "0..*" Emprestimo : registra

@enduml
