/*
gerente
supervisor
assistente - vendedor
caixa - operador de caixa
estoquista 
*/
------------------------------------------------------COMISSÃO E SALÁRIO-----------------------------------------------------
CREATE OR REPLACE FUNCTION COMISSAO(CPF_F VARCHAR(15), DT_I DATE, DT_F DATE)
RETURNS NUMERIC(8,2) AS $$
DECLARE
	COMISSAO NUMERIC;
	CARGO VARCHAR(50);
BEGIN
	SELECT C.NOME INTO CARGO FROM FUNCIONARIO F JOIN CARGO C ON C.COD = F.COD_CARGO WHERE CPF ILIKE CPF_F;
	
	IF NOT EXISTS(SELECT * FROM FUNCIONARIO WHERE CPF ILIKE CPF_F) THEN
		RAISE EXCEPTION 'O FUNCIONARIO NÃO EXISTE.';
	END IF;
	
	IF CARGO ILIKE 'CAIXA' THEN -- CAIXA -> OPERADOR DE CAIXA C = 0.07
		COMISSAO := COALESCE(SUM(VALOR_TOTAL * 0.07),0)::NUMERIC(8,2) FROM PEDIDO P
		JOIN FUNCIONARIO F ON F.COD = P.COD_FUNCIONARIO
		WHERE CPF ILIKE CPF_F 
		AND DATA_HORA BETWEEN DT_I 
		AND DT_F AND PAGO = TRUE;

	ELSIF CARGO ILIKE 'ASSISTENTE' THEN -- ASSISTENTE -> VENDEDOR C = 0.5
		COMISSAO := COALESCE(SUM(VALOR_TOTAL * 0.5),0)::NUMERIC(8,2) FROM PEDIDO P
		JOIN FUNCIONARIO F ON F.COD = P.COD_FUNCIONARIO
		WHERE CPF ILIKE CPF_F 
		AND DATA_HORA BETWEEN DT_I 
		AND DT_F AND PAGO = TRUE;
	
	ELSE --CARGO ILIKE 'GERENTE' OR CARGO ILIKE 'SUPERVISOR' OR CARGO ILIKE 'ESTOQUISTA' THEN
		RAISE EXCEPTION 'O CARGO % NÃO POSSUI COMISSÃO.', CARGO;
	END IF;
	
	RETURN COMISSAO;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION SALARIO(CPF_F VARCHAR(20), DT_I DATE, DT_F DATE)
RETURNS NUMERIC(8,2) AS $$
DECLARE 
	SALARIO_BASE NUMERIC;
	COMISSAO NUMERIC;
	SALARIO_TT NUMERIC;
	MESES INT;
	CARGO VARCHAR(20);
BEGIN 
	SELECT EXTRACT('MONTH' FROM AGE(DT_F,DT_I)) INTO MESES;
	SELECT SALARIO INTO SALARIO_BASE FROM CARGO C JOIN FUNCIONARIO F ON F.COD_CARGO = C.COD WHERE CPF ILIKE CPF_F;
	SELECT C.NOME INTO CARGO FROM FUNCIONARIO F JOIN CARGO C ON C.COD = F.COD_CARGO WHERE CPF ILIKE CPF_F;
	
	IF CARGO ILIKE 'GERENTE' OR CARGO ILIKE 'SUPERVISOR' OR CARGO ILIKE 'ESTOQUISTA' THEN
		SALARIO_TT := SALARIO_BASE * MESES;
	ELSE
		COMISSAO := COMISSAO(CPF_F, DT_I, DT_F);
		SALARIO_TT := (SALARIO_BASE * MESES) + COMISSAO;
	END IF;

	RETURN SALARIO_TT;
END;
$$ LANGUAGE PLPGSQL;
--SELECT SALARIO('987.654.321-09','01-06-2024',CURRENT_DATE)