CREATE TABLE CLIENTE(
	COD SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(15) NOT NULL UNIQUE,
	CONTATO VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL
);
SELECT CADASTRAR('cliente','Maria Silva', '123.456.789-10', '(11) 91234-5678', 'maria.silva@gmail.com') 
SELECT CADASTRAR('CLIENTE','João Oliveira', '987.654.321-00', '(21) 99876-5432', 'joao.oliveira@gmail.com') 
SELECT CADASTRAR('CLIENTE','Ana Santos', '456.789.123-45', '(31) 98765-4321', 'ana.santos@gmail.com') 
SELECT CADASTRAR('CLIENTE','Pedro Souza', '654.321.987-00', '(41) 97654-3210', 'pedro.souza@gmail.com') 
SELECT CADASTRAR('CLIENTE','Mariana Lima', '789.123.456-78', '(51) 96543-2109', 'mariana.lima@gmail.com')
	
CREATE TABLE CARGO(
	COD SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SALARIO NUMERIC(8,2) NOT NULL
);
SELECT CADASTRAR('CARGO','Gerente', 2500.00)
SELECT CADASTRAR('CARGO','Supervisor', 2186.00)
SELECT CADASTRAR('CARGO','Vendedor', 1427.00)
SELECT CADASTRAR('CARGO','Operador de Caixa', 1782.00)
SELECT CADASTRAR('CARGO','Estoquista', 1350.00)

CREATE TABLE LOJA
	COD SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);
SELECT CADASTRAR('LOJA','Loja 1')
SELECT CADASTRAR('LOJA','Loja 2')
SELECT CADASTRAR('LOJA','Loja 3')
SELECT CADASTRAR('LOJA','Loja 4')
SELECT CADASTRAR('LOJA','Loja 5')

CREATE TABLE FUNCIONARIO(
	COD SERIAL NOT NULL PRIMARY KEY,
	COD_CARGO INT NOT NULL REFERENCES CARGO(COD) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	COD_LOJA INT NOT NULL REFERENCES LOJA(COD) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(15) NOT NULL UNIQUE,
	CONTATO VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL
);
SELECT CADASTRAR('FUNCIONARIO','Gerente','Loja 1','João Silva', '123.456.789-01', '(11) 91234-5678', 'joao.silva@email.com')
SELECT CADASTRAR('FUNCIONARIO','Supervisor','Loja 1','Maria Santos', '987.654.321-09', '(22) 98765-4321', 'maria.santos@email.com')
SELECT CADASTRAR('FUNCIONARIO','Vendedor','Loja 2','Carlos Oliveira', '222.333.444-55', '(33) 87654-3210', 'carlos.oliveira@email.com')
SELECT CADASTRAR('FUNCIONARIO','Operador de Caixa','Loja 2','Ana Pereira', '555.666.777-99', '(44) 76543-2109', 'ana.pereira@email.com')
SELECT CADASTRAR('FUNCIONARIO','Estoquista','Loja 3','Pedro Rocha', '111.222.333-44', '(55) 65432-1098', 'pedro.rocha@email.com')
SELECT CADASTRAR('FUNCIONARIO','Gerente','Loja 3','Mariana Costa', '999.888.777-66', '(66) 54321-0987', 'mariana.costa@email.com')
SELECT CADASTRAR('FUNCIONARIO','Supervisor','Loja 4','Lucas Oliveira', '333.222.111-00', '(77) 43210-9876', 'lucas.oliveira@email.com')
SELECT CADASTRAR('FUNCIONARIO','Vendedor','Loja 4','Juliana Pereira', '777.888.999-00', '(88) 32109-8765', 'juliana.pereira@email.com')
SELECT CADASTRAR('FUNCIONARIO','Operador de Caixa','Loja 5','Fernanda Santos', '444.555.666-33', '(99) 21098-7654', 'fernanda.santos@email.com')
SELECT CADASTRAR('FUNCIONARIO','Estoquista','Loja 5','Rafaela Almeida', '666.777.888-11', '(00) 10987-6543', 'rafaela.almeida@email.com')
	
CREATE TABLE PAGAMENTO(
	COD SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);
SELECT CADASTRAR('PAGAMENTO','Cartão de Crédito')
SELECT CADASTRAR('PAGAMENTO','Cartão de Débito')
SELECT CADASTRAR('PAGAMENTO','Dinheiro')
SELECT CADASTRAR('PAGAMENTO','Transferência Bancária')
SELECT CADASTRAR('PAGAMENTO','Pix')

CREATE TABLE CATEGORIA(
	COD SERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO TEXT NOT NULL
);
SELECT CADASTRAR('CATEGORIA','Camisetas', 'Camisetas de diversos estilos e cores')
SELECT CADASTRAR('CATEGORIA','Calças Jeans', 'Calças jeans masculinas e femininas')
SELECT CADASTRAR('CATEGORIA','Vestidos', 'Vestidos elegantes para diversas ocasiões')
SELECT CADASTRAR('CATEGORIA','Sapatos', 'Calçados confortáveis e estilosos')
SELECT CADASTRAR('CATEGORIA','Acessórios', 'Acessórios variados, como bolsas e cintos')

CREATE TABLE PRODUTO(
	COD SERIAL NOT NULL PRIMARY KEY,
	COD_CATEGORIA INT NOT NULL REFERENCES CATEGORIA(COD) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	NOME VARCHAR(50) NOT NULL,
	VALOR_UNITARIO NUMERIC(8,2) NOT NULL
);
SELECT CADASTRAR('PRODUTO','Camisetas','Camiseta Básica', 29.99)
SELECT CADASTRAR('PRODUTO','Camisetas','Camiseta Estampada', 39.99)
SELECT CADASTRAR('PRODUTO','Calças Jeans','Calça Jeans Skinny', 89.99)
SELECT CADASTRAR('PRODUTO','Calças Jeans','Calça Jeans Reta', 79.99)
SELECT CADASTRAR('PRODUTO','Vestidos','Vestido Midi Floral', 129.99)
SELECT CADASTRAR('PRODUTO','Vestidos','Vestido Longo de Festa', 199.99)
SELECT CADASTRAR('PRODUTO','Sapatos','Sapato Social Masculino', 149.99)
SELECT CADASTRAR('PRODUTO','Sapatos','Sapato Anabela Feminino', 119.99)
SELECT CADASTRAR('PRODUTO','Acessórios','Bolsa Transversal', 79.99)
SELECT CADASTRAR('PRODUTO','Acessórios','Cinto de Couro', 49.99)

CREATE TABLE ESTOQUE(
	COD SERIAL NOT NULL PRIMARY KEY, 
	COD_PRODUTO INT NOT NULL REFERENCES PRODUTO(COD) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	COD_LOJA INT NOT NULL REFERENCES LOJA(COD) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	QUANTIDADE INT NOT NULL
);
SELECT CADASTRAR('ESTOQUE','Camiseta Básica','Loja 1',100)
SELECT CADASTRAR('ESTOQUE','Camiseta Estampada','Loja 2',100)
SELECT CADASTRAR('ESTOQUE','Calça Jeans Skinny','Loja 3',100)
SELECT CADASTRAR('ESTOQUE','Calça Jeans Reta','Loja 4',100)
SELECT CADASTRAR('ESTOQUE','Vestido Midi Floral','Loja 5',100)
SELECT CADASTRAR('ESTOQUE','Vestido Longo de Festa','Loja 1',100)
SELECT CADASTRAR('ESTOQUE','Sapato Social Masculino','Loja 2',100)
SELECT CADASTRAR('ESTOQUE','Sapato Anabela Feminino','Loja 3',100)
SELECT CADASTRAR('ESTOQUE','Bolsa Transversal','Loja 4',100)
SELECT CADASTRAR('ESTOQUE','Cinto de Couro','Loja 5',100)
	
CREATE TABLE PEDIDO(
	COD SERIAL NOT NULL PRIMARY KEY,
	COD_CLIENTE INT NOT NULL REFERENCES CLIENTE(COD) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	COD_FUNCIONARIO INT NOT NULL REFERENCES FUNCIONARIO(COD) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	COD_PAGAMENTO INT NOT NULL REFERENCES PAGAMENTO(COD) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	VALOR_TOTAL NUMERIC(8,2) NOT NULL,
	DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PAGO BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE ITEM_PEDIDO(
	COD SERIAL NOT NULL PRIMARY KEY,
	COD_PEDIDO INT NOT NULL REFERENCES PEDIDO(COD) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	COD_ESTOQUE INT NOT NULL REFERENCES ESTOQUE(COD) 
		ON UPDATE CASCADE 
		ON DELETE RESTRICT,
	QUANTIDADE INT NOT NULL,
	VALOR_TOTAL_ITEM NUMERIC(8,2) NOT NULL
);