/*	
'^[^a-zA-Z0-9]+$' - caracteres especiais
'^[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}$' - formato cpf
'^\([0-9]{2}\) [0-9]{10}' - formato contato
'.*[0-9].*' - numeros dentro de uma string
'^[0-9]' - numeros no comeco da string
*/
------------------------------------------------EXCEÇÕES--------------------------------------------------------------

CREATE OR REPLACE FUNCTION VERIFICAR_ATRIBUTOS_INT(ATRIBUTOS VARCHAR[])
RETURNS VOID AS $$ 
DECLARE 
	ATRIBUTO VARCHAR;
BEGIN 
    FOREACH ATRIBUTO IN ARRAY ATRIBUTOS
    LOOP
		IF ATRIBUTO !~ '^[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}$' AND ATRIBUTO !~ '^\([0-9]{2}\) [0-9]{5}\-[0-9]{4}$' THEN --IF ATRIBUTO !~ '^[0-9\.\(\)\-\s]+$' THEN
			RAISE EXCEPTION 'ERROR: ATRIBUTO DE VALOR INVÁLIDO %.', ATRIBUTO;
		ELSIF ATRIBUTO = '' OR TRIM(ATRIBUTO) = '' THEN
			RAISE EXCEPTION 'ERROR: ATRIBUTO VÁZIO.';
		END IF;
    END LOOP;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION TG_VERIFICAR_ATRIBUTOS_INT()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM VERIFICAR_ATRIBUTOS_INT(ARRAY[NEW.CPF, NEW.CONTATO]);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql; 

--TRIGGER BY TABLE
CREATE TRIGGER TG_CHECK_INT
BEFORE INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
EXECUTE FUNCTION TG_VERIFICAR_ATRIBUTOS_INT()

CREATE TRIGGER TG_CHECK_INT
BEFORE INSERT OR UPDATE ON FUNCIONARIO
FOR EACH ROW
EXECUTE FUNCTION TG_VERIFICAR_ATRIBUTOS_INT()

---------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION VERIFICAR_ATRIBUTOS_VARCHAR(ATRIBUTO VARCHAR)
RETURNS VOID AS $$
BEGIN
	IF ATRIBUTO !~ '^[a-zA-Z]+$' THEN 
		RAISE EXCEPTION 'ERROR: ATRIBUTO DE VALOR INVÁLIDO %', ATRIBUTO;
	ELSIF ATRIBUTO = '' OR TRIM(ATRIBUTO) = '' THEN
		RAISE EXCEPTION 'ERROR: ATRIBUTO VAZIO.';
	END IF;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION TG_VERIFICAR_ATRIBUTOS_VARCHAR()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM VERIFICAR_ATRIBUTOS_VARCHAR(NEW.NOME);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

--TRIGGER BY TABLE
CREATE TRIGGER TRIGGER_CHECK_VARCHAR
BEFORE INSERT OR UPDATE ON CLIENTE
FOR EACH ROW
EXECUTE FUNCTION TG_VERIFICAR_ATRIBUTOS_VARCHAR()

CREATE TRIGGER TRIGGER_CHECK_VARCHAR
BEFORE INSERT OR UPDATE ON CARGO
FOR EACH ROW
EXECUTE FUNCTION TG_VERIFICAR_ATRIBUTOS_VARCHAR()

CREATE TRIGGER TRIGGER_CHECK_VARCHAR
BEFORE INSERT OR UPDATE ON FUNCIONARIO
FOR EACH ROW
EXECUTE FUNCTION TG_VERIFICAR_ATRIBUTOS_VARCHAR()

CREATE TRIGGER TRIGGER_CHECK_VARCHAR
BEFORE INSERT OR UPDATE ON PAGAMENTO
FOR EACH ROW
EXECUTE FUNCTION TG_VERIFICAR_ATRIBUTOS_VARCHAR()

CREATE TRIGGER TRIGGER_CHECK_VARCHAR
BEFORE INSERT OR UPDATE ON CATEGORIA
FOR EACH ROW
EXECUTE FUNCTION TG_VERIFICAR_ATRIBUTOS_VARCHAR()

CREATE TRIGGER TRIGGER_CHECK_VARCHAR
BEFORE INSERT OR UPDATE ON PRODUTO
FOR EACH ROW
EXECUTE FUNCTION TG_VERIFICAR_ATRIBUTOS_VARCHAR()