-----------------------------------------------CRIAR E FINALIZAR PEDIDO-------------------------------------------
CREATE OR REPLACE FUNCTION ADD_PEDIDO(
	CPF_C VARCHAR(15), 
	NOME_P VARCHAR(50), 
	QUANT_V INT, 
	NOME_PAG VARCHAR(50), 
	CPF_F VARCHAR(15),
	QUANT_PARCELA INT DEFAULT 0)
RETURNS VOID AS $$
DECLARE
	COD_PDD INT; --PEDIDO
	COD_C INT;
	COD_P INT;
	COD_F INT;
	COD_E INT;
	COD_L INT;
	NOME_L VARCHAR;
	QUANT_E INT;
	VALOR_UNIT NUMERIC(8,2);
	COD_PAG INT;
BEGIN
	SELECT COD INTO COD_C FROM CLIENTE WHERE CPF ILIKE CPF_C;
	SELECT COD INTO COD_F FROM FUNCIONARIO WHERE CPF ILIKE CPF_F;
	SELECT COD INTO COD_P FROM PRODUTO WHERE NOME ILIKE NOME_P;
	SELECT COD INTO COD_PDD FROM PEDIDO WHERE COD_CLIENTE = COD_C AND PAGO = FALSE;
	SELECT COD INTO COD_E FROM ESTOQUE WHERE COD_PRODUTO = COD_P;
	SELECT L.COD INTO COD_L FROM LOJA L JOIN FUNCIONARIO F ON F.COD_LOJA = L.COD JOIN ESTOQUE E ON E.COD_LOJA = L.COD WHERE F.COD = COD_F;
	SELECT L.NOME INTO NOME_L FROM LOJA L JOIN FUNCIONARIO F ON F.COD_LOJA = L.COD JOIN ESTOQUE E ON E.COD_LOJA = L.COD WHERE F.COD = COD_F;

	SELECT QUANTIDADE INTO QUANT_E FROM ESTOQUE WHERE COD_PRODUTO = COD_P;
	SELECT VALOR_UNITARIO INTO VALOR_UNIT FROM PRODUTO WHERE COD = COD_P;
	SELECT COD INTO COD_PAG FROM PAGAMENTO WHERE NOME ILIKE NOME_PAG;
		
	IF EXISTS(SELECT * FROM CLIENTE WHERE COD = COD_C) THEN
		IF EXISTS(SELECT * FROM FUNCIONARIO F JOIN CARGO C ON C.COD = F.COD_CARGO JOIN LOJA L ON L.COD = F.COD_LOJA WHERE F.COD = COD_F AND C.NOME ILIKE 'Operador de Caixa' ) THEN
	
			--VERIFICA SE O PRODUTO INFORMADO EXISTE NA MESMA LOJA QUE O FUNCIONARIO INFORMADO
			IF EXISTS(SELECT * FROM PRODUTO P JOIN ESTOQUE E ON P.COD = E.COD_PRODUTO JOIN FUNCIONARIO F ON F.COD_LOJA = E.COD_LOJA WHERE E.COD_LOJA = F.COD_LOJA AND E.COD_PRODUTO = COD_P AND F.COD = COD_F) THEN
				
				IF (QUANT_E >= QUANT_V) THEN
					IF EXISTS(SELECT * FROM PEDIDO WHERE COD = COD_PDD) THEN
						IF NOT EXISTS(SELECT * FROM PAGAMENTO WHERE COD = COD_PAG) THEN
							RAISE EXCEPTION 'O TIPO DE PAGAMENTO ''%'' NÃO EXISTE.', NOME_PAG;
						ELSE
							IF NOT EXISTS(SELECT * FROM PEDIDO P JOIN CLIENTE C ON C.COD = P.COD_CLIENTE) THEN
								RAISE EXCEPTION 'O PEDIDO % JÁ EXISTE, PORÉM OS DADOS NÃO CORRESPONDEM', COD_PDD;
							ELSIF EXISTS(SELECT * FROM ITEM_PEDIDO IP JOIN ESTOQUE E ON E.COD = IP.COD_ESTOQUE JOIN PRODUTO P ON P.COD = E.COD_PRODUTO WHERE IP.COD = COD_PDD AND COD_P = E.COD_PRODUTO) THEN
								UPDATE ITEM_PEDIDO SET 
									QUANTIDADE = QUANTIDADE + QUANT_V,
									VALOR_TOTAL_ITEM = VALOR_TOTAL_ITEM + (VALOR_UNIT * QUANT_V)
								WHERE COD_PEDIDO = COD_PDD AND COD_ESTOQUE = COD_E; 
								RAISE INFO 'PEDIDO ATUALIZADO COM SUCESSO.';
			
							ELSE 
								INSERT INTO ITEM_PEDIDO(COD_PEDIDO, COD_ESTOQUE, QUANTIDADE, VALOR_TOTAL_ITEM) VALUES(COD_PDD, COD_E, QUANT_V, (QUANT_V * VALOR_UNIT));
								RAISE INFO 'PEDIDO ADICIONADO COM SUCESSO.';
			
							END IF;
		
							UPDATE PEDIDO SET VALOR_TOTAL = VALOR_TOTAL + (VALOR_UNIT * QUANT_V) WHERE COD = COD_PDD;
						END IF;
					ELSE 
						-- PEDIDO
						INSERT INTO PEDIDO(COD_CLIENTE, COD_FUNCIONARIO, COD_PAGAMENTO, VALOR_TOTAL)
						VALUES(COD_C, COD_F, COD_PAG, (VALOR_UNIT * QUANT_V)) RETURNING COD INTO COD_PDD;
			
						-- ITEM_PEDIDO
						INSERT INTO ITEM_PEDIDO(COD_PEDIDO, COD_ESTOQUE, QUANTIDADE, VALOR_TOTAL_ITEM)
						VALUES(COD_PDD, COD_E, QUANT_V, (VALOR_UNIT * QUANT_V));

						-- CREDIARIO
						IF NOME_PAG ILIKE 'CREDIÁRIO' THEN
							PERFORM CARNE_CREDIARIO(COD_PDD, QUANT_PARCELA);
							RAISE INFO 'PEDIDO E CREDIÁRIO CRIADOS COM SUCESSO.';
						ELSE		
							RAISE INFO 'PEDIDO CRIADO COM SUCESSO.';
						END IF;
					END IF;
					--DECREMENTA O ESTOQUE
					UPDATE ESTOQUE SET QUANTIDADE = QUANTIDADE - QUANT_V WHERE COD = COD_E;
		
				ELSE
					RAISE EXCEPTION 'QUANTIDADE EM ESTOQUE INSUFICIENTE.';
				END IF;
			ELSE
				RAISE EXCEPTION 'O PRODUTO INFORMADO ''%'' NÃO EXISTE NA LOJA ''%''',NOME_P, NOME_L;
			END IF;
	
		ELSIF EXISTS(SELECT * FROM FUNCIONARIO F JOIN CARGO C ON C.COD = F.COD_CARGO JOIN LOJA L ON L.COD = F.COD_LOJA WHERE F.COD = COD_F AND C.NOME NOT ILIKE 'Operador de Caixa' ) THEN
			RAISE EXCEPTION 'O FUNCIONÁRIO ''%'' NÃO PERTENCE AO SETOR.', CPF_F;
		ELSE
			RAISE EXCEPTION 'O FUNCIONÁRIO ''%'' NÃO EXISTE.', CPF_F;
		END IF;
	ELSE
		RAISE EXCEPTION 'O CLIENTE ''%'' NÃO EXISTE.', CPF_C;
	END IF;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION FINALIZAR_PEDIDO(CPF_C VARCHAR(15))
RETURNS TABLE (
	"n°Pedido" VARCHAR, 
	Cliente VARCHAR(100), 
	Produto VARCHAR(100), 
	Valor NUMERIC(8,2), 
	Quantidade INT, 
	Total NUMERIC(8,2), 
	Data VARCHAR(10), 
	Hora VARCHAR(8), 
	Funcionario VARCHAR(100),
	Pago BOOLEAN) AS $$
DECLARE
	COD_C INT;
	COD_P INT;
BEGIN 
	SELECT COD INTO COD_C FROM CLIENTE WHERE CPF ILIKE CPF_C;
	SELECT COD INTO COD_P FROM PEDIDO P WHERE COD_CLIENTE = COD_C AND P.PAGO = FALSE;

	IF EXISTS(SELECT * FROM CLIENTE WHERE COD = COD_C) THEN
		IF EXISTS(SELECT * FROM PEDIDO P WHERE COD = COD_P AND P.PAGO = FALSE) THEN
			UPDATE PEDIDO SET PAGO = TRUE WHERE COD = COD_P;
			RAISE INFO 'PEDIDO FINALIZADO COM SUCESSO.';
			-- RETORNA A NOTA FISCAL DO PEDIDO
			RETURN QUERY
		 		SELECT * FROM NOTA_FISCAL(CPF_C);
		ELSE
			RAISE EXCEPTION 'O CLIENTE ''%'' NÃO POSSUI PEDIDO EM ABERTO.', CPF_C;
		END IF;
	ELSE
		RAISE EXCEPTION 'O CLIENTE ''%'' NÃO EXISTE.',CPF_C;
	END IF;
END;
$$ LANGUAGE PLPGSQL;
-----------------------------------------------------NOTA FISCAL----------------------------------------------------------------------

CREATE OR REPLACE FUNCTION NOTA_FISCAL(CPF_C VARCHAR(15))
RETURNS TABLE (
	"n°Pedido" VARCHAR, 
	Cliente VARCHAR(100), 
	Produto VARCHAR(100), 
	Valor NUMERIC(8,2), 
	Quantidade INT, 
	Total NUMERIC(8,2), 
	Data VARCHAR(10), 
	Hora VARCHAR(8), 
	Funcionario VARCHAR(100), 
	Pago BOOLEAN) AS $$
DECLARE
	COD_C INT;
	COD_PDD INT;
BEGIN
	SELECT COD INTO COD_C FROM CLIENTE WHERE CPF = CPF_C;
	SELECT P.COD INTO COD_PDD FROM PEDIDO P JOIN CLIENTE C ON C.COD = P.COD_CLIENTE WHERE C.COD = COD_C; --AND P.PAGO = FALSE;

	IF EXISTS(SELECT * FROM CLIENTE WHERE COD = COD_C) THEN
		IF EXISTS(SELECT * FROM PEDIDO WHERE COD = COD_PDD) THEN
			RETURN QUERY
				SELECT 
					(PDD.Pedido)::VARCHAR "n°Pedido", 
					PDD.Cliente, 
					PDD.Produto, 
					PDD.Valor, 
					PDD.Quantidade, 
					PDD.Total, 
					PDD.Data, 
					PDD.Hora,
					PDD.Funcionario,
					PDD.Pago
				FROM PEDIDOS PDD
				WHERE PDD.Pedido = COD_PDD;
		ELSE
			RAISE EXCEPTION 'O CLIENTE % NÃO POSSUI VENDAS EM ABERTO.', CPF_C;
		END IF;
	ELSE
		RAISE EXCEPTION 'O CLIENTE % NÃO EXISTE.', CPF_C;
	END IF;
END;
$$ LANGUAGE PLPGSQL;


----------------------------------------------------FUNÇÃO CREDIÁRIO---------------------------------------------------------------
CREATE OR REPLACE FUNCTION CARNE_CREDIARIO(COD_P INT, QUANT_P INT)
RETURNS VOID AS $$
DECLARE
	COD_PDD INT; -- PEDIDO
	COD_C INT; -- CREDIARIO
	TAXA_J INT;
	VALOR_J INT;
	VALOR_P NUMERIC;
	VALOR_TT NUMERIC;
	DATA_V TIMESTAMP := CURRENT_TIMESTAMP;
BEGIN
	SELECT COD INTO COD_PDD FROM PEDIDO WHERE COD = COD_PDD;
	SELECT COD INTO COD_C FROM CREDIARIO WHERE COD_PEDIDO = COD_PDD;
	SELECT VALOR_TOTAL INTO VALOR_TT FROM PEDIDO WHERE COD = COD_P;

	IF QUANT_P > 0 AND QUANT_P <= 6 THEN

		VALOR_P := (VALOR_TT / QUANT_P);
		INSERT INTO CREDIARIO(COD_PEDIDO, QUANTIDADE_PARCELA, VALOR_PARCELA,DATA_VENCIMENTO) VALUES(COD_PDD, QUANT_P, VALOR_P, DATA_V);
		RAISE INFO 'PARCELAS DO CREDIÁRIO CRIADAS COM SUCESSO.';

	ELSIF QUANT_P > 6 AND QUANT_P <= 12 THEN

		TAXA_J := 0.005;
		VALOR_J := VALOR_TT * TAXA_J;
		VALOR_P := (VALOR_TT + VALOR_J) / QUANT_P;

		FOR PARCELAS IN 1..QUANT_P LOOP
			INSERT INTO CREDIARIO(COD_PEDIDO, QUANTIDADE_PARCELA, VALOR_PARCELA,DATA_VENCIMENTO) 
			VALUES(COD_PDD, QUANT_P, VALOR_P, DATA_V);
			DATA_V := DATA_V + INTERVAL '1 MONTH';
		END LOOP;

		RAISE INFO 'PARCELAS DO CREDIÁRIO CRIADAS COM SUCESSO.';
	ELSE
		RAISE EXCEPTION 'QUANTIDADE DE PARCELAS NÃO PERMITIDAS.';
	END IF;
END;
$$ LANGUAGE PLPGSQL;
SELECT * FROM PEDIDO
SELECT * FROM CREDIARIO

SELECT ADD_PEDIDO('987.654.321-00', 'Camiseta Básica', 2, 'Crediário','456.789.012-34', 6)

-----------------------------------------------FINALIZAR CREDIÁRIO--------------------------------------------------------------

CREATE OR REPLACE FUNCTION PAGAR_CREDIARIO(CPF_C VARCHAR(15), DATA_PAG TIMESTAMP)
RETURNS VOID AS $$
DECLARE
	VALOR_P NUMERIC;
	JUROS_ATRASO NUMERIC;
	DIAS_ATRASO INT;
	COD_C INT;
BEGIN
	SELECT VALOR_PARCELA INTO VALOR_P FROM CREDIARIO C JOIN PEDIDO P ON P.COD = C.COD_PEDIDO JOIN CLIENTE CLI ON P.COD_CLIENTE = C.COD WHERE CPF ILIKE CPF_C;
	SELECT EXTRACT(DAY FROM DATA_PAGA - DATA_VENCIMENTO) INTO DIAS_ATRASO FROM CREDIARIO;
	SELECT COD INTO COD_C FROM CREDIARIO C JOIN PEDIDO P ON P.COD = C.COD_PEDIDO JOIN CLIENTE CLI ON P.COD_CLIENTE = C.COD WHERE CPF ILIKE CPF_C;

	--VERIFICAR DATA DO PAGAMENTO, SE PASSAR = JUROS, SE JA ESTIVER PAGA = EXIBIR MENSAGEM
	
	IF DIAS_ATRASO > 0 THEN
		JUROS_ATRASO := VALOR_P * 0.005 * DIAS_ATRASO;
	ELSE
		JUROS_ATRASO := 0;
	END IF;

	UPDATE CREDIARIO SET
		DATA_PAGAMENTO = DT_PAG,
		VALOR_PARCELA = VALOR_P + JUROS_ATRASO,
		QUANTIDADE_PARCELA = QUANTIDADE_PARCELA - 1
	WHERE COD = COD_C ;
	
	RAISE INFO 'PARCELA PAGA COM SUCESSO. JUROS POR ATRASO %.', JUROS_ATRASO;
END;
$$ LANGUAGE PLPGSQL;