-----------------------------------------------------RELATÓRIOS------------------------------------------------------
--FUNCIONARIO
CREATE OR REPLACE VIEW VER_FUNCIONARIOS AS
	SELECT F.COD as "n°Id", F.NOME as Nome, F.CPF as cpf, F.CONTATO as Telefone, F.EMAIL as Email, C.NOME as Cargo, C.SALARIO as Salario
	FROM FUNCIONARIO F
		JOIN CARGO C ON C.COD = F.COD_CARGO
		JOIN LOJA L ON L.COD = F.COD_LOJA
	ORDER BY F.NOME;

--CLIENTE
CREATE OR REPLACE VIEW VER_CLIENTE AS
	SELECT C.COD as "n°Id", C.NOME as Nome, C.CPF as cpf, C.CONTATO as Telefone, C.EMAIL as Email
	FROM CLIENTE C ORDER BY C.NOME;

--PEDIDO
CREATE OR REPLACE FUNCTION RELATORIO_PEDIDO(DT_I DATE, DT_F DATE)
RETURNS TABLE(
	"Produto" VARCHAR(100), 
	"Quantidade" INT, 
	"Valor Total" NUMERIC(8,2), 
	"Média Quantidade" INT, 
	"Média Valor Total" NUMERIC (8,2)) 
AS $$
DECLARE
	DIAS INT;
BEGIN
	SELECT EXTRACT('DAY' FROM AGE(DT_F,DT_I)) INTO DIAS;

	RETURN QUERY 
		SELECT 
			PDT.NOME PRODUTO, 
			SUM(IP.QUANTIDADE)::INT QUANTIDADE, 	
			SUM(IP.QUANTIDADE * PDT.VALOR_UNITARIO)::NUMERIC(8,2) VALOR_TOTAL,
			AVG(IP.QUANTIDADE/DIAS)::INT MEDIA_QUANTIDADE,
			AVG((IP.QUANTIDADE * PDT.VALOR_UNITARIO)/DIAS)::NUMERIC(8,2) MEDIA_VALOR_TOTAL
		FROM PEDIDO P
			JOIN ITEM_PEDIDO IP ON P.COD = IP.COD_PEDIDO
			JOIN ESTOQUE E ON E.COD = IP.COD_ESTOQUE
			JOIN PRODUTO PDT ON PDT.COD = E.COD_PRODUTO
		WHERE PAGO = TRUE AND DATA_HORA BETWEEN DT_I AND DT_F
		GROUP BY PRODUTO;
END;
$$ LANGUAGE PLPGSQL;