@startuml DC - Cadastro de Funcionarios

class Funcionario {
    +nome: String
    +cpf: String
    +cargo: String
    +salario: Float
}

class Gerente {
    +gerenciar(): void
}

class Departamento {
    +nome: String
    +gerente: Gerente
}

class RH {
    +departamento: Departamento
    +gerenciarFuncionarios():void
}


Funcionario <|-- Gerente
Departamento "1..1" -- "1..1" Funcionario : gerencia >
RH --|> Departamento
Gerente "1" --> "1" Departamento : tem > 


@enduml
